-- Hand-written (NOT generated by `prisma migrate diff`, which produced a destructive
-- drop/recreate for this rename - see git history of this file for that draft). Every
-- statement below is a pure rename: no table is dropped and no column value is touched,
-- so all existing rows and their data survive untouched.
--
-- What is being fixed: the word "project" already meant "OePlan" in ExecutionSchedule,
-- OpenMeeting, Document and Report (their projectId/project pointed at OePlan). Meanwhile
-- the UI now calls PlannedEngagement "Project". Renaming only PlannedEngagement would have
-- made that collision worse, so both sides move here:
--   PlannedEngagement -> Project              (table + the two FKs pointing at it)
--   OePlan's old "project" link -> "oePlan" on every table that actually meant OePlan

-- 1. The table the UI has called "Project" since the last release.
ALTER TABLE "PlannedEngagement" RENAME TO "Project";

-- 2. OePlan's own link up to its parent Project.
ALTER TABLE "OePlan" RENAME COLUMN "plannedEngagementId" TO "projectId";

-- 3. Columns that were misleadingly called "project*" but have always pointed at OePlan.
ALTER TABLE "Document" RENAME COLUMN "projectId" TO "oePlanId";
ALTER TABLE "Report" RENAME COLUMN "projectId" TO "oePlanId";
ALTER TABLE "ExecutionSchedule" RENAME COLUMN "projectId" TO "oePlanId";
ALTER TABLE "OpenMeeting" RENAME COLUMN "projectId" TO "oePlanId";

-- 4. Permission keys: planned-engagements:* -> projects:*. Done as
-- insert-new/reassign-grants/delete-old (never dropping a still-referenced key) so any
-- existing GroupPermission row is never left pointing at a deleted foreign key.
INSERT INTO "Permission" ("key", "description")
SELECT 'projects:' || split_part("key", ':', 2), "description"
FROM "Permission"
WHERE "key" LIKE 'planned-engagements:%'
ON CONFLICT ("key") DO NOTHING;

UPDATE "GroupPermission"
SET "permissionKey" = 'projects:' || split_part("permissionKey", ':', 2)
WHERE "permissionKey" LIKE 'planned-engagements:%';

DELETE FROM "Permission" WHERE "key" LIKE 'planned-engagements:%';
